#!/bin/sh

cp .tmux.conf ~
cp .inputrc ~

# neovim
mkdir -p ~/.local/bin
curl -Lo ~/.local/bin/nvim https://github.com/neovim/neovim/releases/download/v0.9.5/nvim.appimage
chmod 777 ~/.local/bin/nvim
cp -r .config/nvim ~/.config
