# https://nix.dev/manual/nix/2.26/command-ref/conf-file
experimental-features = nix-command flakes

# https://github.com/ropensci/rix/blob/02adc4b1f45f059452054d41b86fee3212d74d2e/inst/extdata/nix.conf
extra-substituters = https://rstats-on-nix.cachix.org
extra-trusted-public-keys = rstats-on-nix.cachix.org-1:vdiiVgocg6WeJrODIqdprZRUrhi1JzhBnXv7aWI6+F0=
